[package]
name = "gnomad_lite_schema"
version = "0.1.0"
edition = "2024"

[dependencies]
jsonschema = "0.40.0"
serde = { version = "1.0.228", features = ["serde_derive"] }
serde_json = "1.0.149"

[dev-dependencies]
factori = "1.1.0"
